"""Master Init for Phase 2

Revision ID: 19db4b07d623
Revises: 
Create Date: 2026-03-02 19:07:28.999769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19db4b07d623'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('candidate_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(length=100), nullable=True),
    sa.Column('office_sought', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('election_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index(op.f('ix_candidates_candidate_id'), 'candidates', ['candidate_id'], unique=False)
    op.create_table('counties',
    sa.Column('county_name', sa.String(length=100), nullable=False),
    sa.Column('registered_voters', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('county_name')
    )
    op.create_index(op.f('ix_counties_county_name'), 'counties', ['county_name'], unique=False)
    op.create_table('donations',
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.String(length=50), nullable=True),
    sa.Column('candidate_id', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('election_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_index(op.f('ix_donations_donation_id'), 'donations', ['donation_id'], unique=False)
    op.create_table('donors',
    sa.Column('donor_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('home_county', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('donor_id')
    )
    op.create_index(op.f('ix_donors_donor_id'), 'donors', ['donor_id'], unique=False)
    op.create_table('election_cycles',
    sa.Column('election_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('election_year')
    )
    op.create_index(op.f('ix_election_cycles_election_year'), 'election_cycles', ['election_year'], unique=False)
    op.create_table('simulation_parameters',
    sa.Column('parameter', sa.String(length=100), nullable=False),
    sa.Column('default_value', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('parameter')
    )
    op.create_index(op.f('ix_simulation_parameters_parameter'), 'simulation_parameters', ['parameter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_parameters_parameter'), table_name='simulation_parameters')
    op.drop_table('simulation_parameters')
    op.drop_index(op.f('ix_election_cycles_election_year'), table_name='election_cycles')
    op.drop_table('election_cycles')
    op.drop_index(op.f('ix_donors_donor_id'), table_name='donors')
    op.drop_table('donors')
    op.drop_index(op.f('ix_donations_donation_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_counties_county_name'), table_name='counties')
    op.drop_table('counties')
    op.drop_index(op.f('ix_candidates_candidate_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
